version: '3'
services:
  backend:
    build: ./backend
    environment:
      - FRONTEND=https://truthslie.site
      - VIRTUAL_HOST=api.truthslie.site
      - PORT=8010
    ports:
        - "8010:8010"
    networks:
      - nginx-proxy
    volumes:
      - ./backend/app:/code/app
    restart: on-failure
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND=https://api.truthslie.site
      - REACT_APP_WSOCK=wss://api.truthslie.site/ws
      - VIRTUAL_HOST=truthslie.site
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - nginx-proxy
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure

networks:
  nginx-proxy:
    external: true
