version: '3'
services:
  backend:
    build: ./backend
    environment:
      - FRONTEND=http://localhost:3000
      - DEBUG=1
      - BASIC_AUTH_USER=changeme
      - BASIC_AUTH_PASSWORD=changeme
    ports:
        - "8010:8010"
    volumes:
      - ./backend/app:/code/app
    restart: on-failure
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND=http://localhost:8010
      - REACT_APP_WSOCK=ws://localhost:8010/ws
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
